version: '3.9'
services:
    bot:
        image: rongbot-test
        restart: always
        depends_on:
            - db
            - webapp
    webapp:
        image: rongwebapp-test
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        # volumes:
        #     - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/