version: '3.9'
services:
    bot:
        image: rongbot
        restart: always
        depends_on:
            db:
                condition: service_healthy
        depends_on:
            - webapp
    webapp:
        image: rongwebapp
        ports:
            - 8000:8000
        dns:
            - 8.8.8.8
            - 4.4.4.4
        restart: always
        depends_on:
            db:
                condition: service_healthy
        
    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
volumes:
    pg_data: