version: '3'
services:
    bot:
        image: scratch
        restart: always
        depends_on: db
    webapp:
        image: scratch
        restart: always
        depends_on: db
    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/