version: '3.9'
services:
    bot:
        image: rongbot
        restart: always
        depends_on:
            db:
                condition: service_healthy
        depends_on:
            - webapp
        environment:
            - DB_NAME
            - DB_USER
            - DB_PASSWORD
            - BOT_TOKEN
    webapp:
        image: rongwebapp
        ports:
            - ${WEBAPP_OUTPORT}:8000
        dns:
            - 8.8.8.8
            - 4.4.4.4
        restart: always
        environment:
            - DB_NAME
            - DB_USER
            - DB_PASSWORD
            - ALLOWED_HOSTS
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:latest
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - ${DB_OUTPORT}:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
volumes:
    pg_data:
