# Generated by Django 3.2 on 2021-04-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClanBattleSchedule',
            fields=[
                ('id', models.AutoField(db_column='clan_battle_id', primary_key=True, serialize=False)),
                ('release_month', models.IntegerField()),
                ('last_cb', models.IntegerField(db_column='last_clan_battle_id')),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
            ],
            options={
                'db_table': 'redive_en"."clan_battle_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(db_column='unit_id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='unit_name')),
            ],
            options={
                'db_table': 'redive_en"."unit_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform_id', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClanBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.clan')),
                ('game_battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='rong.clanbattleschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('is_lead', models.BooleanField()),
                ('group_num', models.IntegerField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members',
                                           to='rong.clan')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_available', models.TextField()),
                ('available_length', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClanCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rong.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClanBattleScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_lap', models.IntegerField()),
                ('boss_number', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('clan_battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.clanbattle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClanBattleComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_lap', models.IntegerField()),
                ('boss_number', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('borrowed_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='borrowedcomps', to='rong.unit')),
                ('clan_battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.clanbattle')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.member')),
                ('unit1',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit1comps',
                                   to='rong.unit')),
                ('unit2',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit2comps',
                                   to='rong.unit')),
                ('unit3',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit3comps',
                                   to='rong.unit')),
                ('unit4',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit4comps',
                                   to='rong.unit')),
            ],
        ),
        migrations.AddField(
            model_name='clan',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='clans_administrated', to='rong.member'),
        ),
        migrations.AddField(
            model_name='clan',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.clancollection'),
        ),
        migrations.CreateModel(
            name='AvailableUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('star', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('equip_1', models.IntegerField()),
                ('equip_2', models.IntegerField()),
                ('equip_3', models.IntegerField()),
                ('equip_4', models.IntegerField()),
                ('equip_5', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.unit')),
            ],
        ),
    ]
