# Generated by Django 3.2 on 2021-04-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0002_auto_20210425_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberschedule',
            name='available_length',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='memberschedule',
            name='time_available',
            field=models.TimeField(),
        ),
    ]
