# Generated by Django 3.2 on 2021-05-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0005_clanbattlecomp_borrowed_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='princessarenacomp',
            name='bracket',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
