# Generated by Django 3.2 on 2021-05-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0006_princessarenacomp_bracket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoxUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveIntegerField(null=True)),
                ('level', models.PositiveIntegerField(null=True)),
                ('star', models.PositiveIntegerField(null=True)),
                ('rank', models.PositiveIntegerField(null=True)),
                ('bond', models.PositiveIntegerField(null=True)),
                ('equip1', models.PositiveIntegerField(null=True)),
                ('equip2', models.PositiveIntegerField(null=True)),
                ('equip3', models.PositiveIntegerField(null=True)),
                ('equip4', models.PositiveIntegerField(null=True)),
                ('equip5', models.PositiveIntegerField(null=True)),
                ('equip6', models.PositiveIntegerField(null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.box')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField()),
                ('group_num', models.PositiveIntegerField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.clan')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('clans', models.ManyToManyField(through='rong.ClanMember', to='rong.Clan')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='clan',
        ),
        migrations.RemoveField(
            model_name='clanbattlescore',
            name='member',
        ),
        migrations.DeleteModel(
            name='AvailableUnit',
        ),
        migrations.AddField(
            model_name='clanmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.user'),
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.user'),
        ),
        migrations.AddField(
            model_name='clan',
            name='members',
            field=models.ManyToManyField(through='rong.ClanMember', to='rong.User'),
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rong.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlearenacounter',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rong.user'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='clans_administrated', to='rong.user'),
        ),
        migrations.AlterField(
            model_name='clanbattlecomp',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.user'),
        ),
        migrations.AlterField(
            model_name='clancollection',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rong.user'),
        ),
        migrations.AlterField(
            model_name='memberschedule',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rong.clanmember'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddConstraint(
            model_name='clanmember',
            constraint=models.UniqueConstraint(fields=('user', 'clan'), name='unique user clan'),
        ),
        migrations.AddConstraint(
            model_name='boxunit',
            constraint=models.UniqueConstraint(fields=('box', 'unit'), name='unique box unit'),
        ),
    ]
