# Generated by Django 3.2 on 2021-05-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0007_auto_20210505_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRoleMember',
            fields=[
                ('server_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('role_id', models.CharField(max_length=30)),
                ('member_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rongbot"."discord_role_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordServerRoles',
            fields=[
                ('server_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('role_id', models.CharField(max_length=30)),
                ('role_name', models.TextField()),
            ],
            options={
                'db_table': 'rongbot"."discord_server_roles',
                'managed': False,
            },
        ),
    ]
