# Generated by Django 3.2 on 2021-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0008_discordrolemember_discordserverroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmember',
            name='group_num',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
