# Generated by Django 3.2 on 2021-05-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0012_rename_last_updated_princessarenacomp_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_pic',
            field=models.CharField(default='105811', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='single_mode',
            field=models.BooleanField(default=True),
        ),
    ]
