# Generated by Django 3.2 on 2021-05-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0016_auto_20210528_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanbattle',
            name='current_boss',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='current_hp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='current_lap',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
