# Generated by Django 3.2 on 2021-05-28 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0018_auto_20210528_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanbattle',
            name='game_battle',
        ),
    ]
