# Generated by Django 3.2 on 2021-05-28 03:26

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import rong.models.clan_battle_score


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0019_remove_clanbattle_game_battle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanbattlescore',
            name='is_carryover',
        ),
        migrations.RemoveField(
            model_name='clanbattlescore',
            name='is_last_hit',
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='hit_type',
            field=django_enum_choices.fields.EnumChoiceField(
                choice_builder=django_enum_choices.choice_builders.value_value,
                choices=[('Normal', 'Normal'), ('Last Hit', 'Last Hit'), ('Carryover', 'Carryover')],
                default=rong.models.clan_battle_score.ClanBattleHitType['NORMAL'],
                enum_class=rong.models.clan_battle_score.ClanBattleHitType, max_length=9),
        ),
    ]
