# Generated by Django 3.2 on 2021-06-01 06:49

from enum import unique
from django.db import migrations
import django_extensions.db.fields

def fill_slug_fields(apps, schema_editor):
    for model_name in ["Clan", "ClanCollection"]:
        model = apps.get_model("rong", model_name)
        for row in model.objects.all():
            # force create slug
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0021_auto_20210528_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='clancollection',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.RunPython(fill_slug_fields),
    ]
