# Generated by Django 3.2 on 2021-06-01 07:23

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0023_auto_20210601_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanbattle',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
                                                            populate_from=['clan__name', 'name'], unique=True),
        ),
    ]
