# Generated by Django 3.2 on 2021-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0025_cnclanbattleperiod_enclanbattleperiod_jpclanbattleperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNClanBattleMapData',
            fields=[
                ('id', models.IntegerField(db_column='clan_battle_id', primary_key=True, serialize=False)),
                ('lap_num_from', models.IntegerField()),
                ('lap_num_to', models.IntegerField()),
                ('wave_group_id_1', models.IntegerField()),
                ('score_coefficient_1', models.FloatField()),
                ('wave_group_id_2', models.IntegerField()),
                ('score_coefficient_2', models.FloatField()),
                ('wave_group_id_3', models.IntegerField()),
                ('score_coefficient_3', models.FloatField()),
                ('wave_group_id_4', models.IntegerField()),
                ('score_coefficient_4', models.FloatField()),
                ('wave_group_id_5', models.IntegerField()),
                ('score_coefficient_5', models.FloatField()),
            ],
            options={
                'db_table': 'redive_cn"."clan_battle_2_map_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CNEnemyParameter',
            fields=[
                ('id', models.IntegerField(db_column='enemy_id', primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField()),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('pdef', models.IntegerField(db_column='def')),
                ('mdef', models.IntegerField(db_column='magic_def')),
            ],
            options={
                'db_table': 'redive_cn"."enemy_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CNWaveGroupData',
            fields=[
                ('id', models.IntegerField(db_column='wave_group_id', primary_key=True, serialize=False)),
                ('odds', models.IntegerField()),
                ('enemy_id_1', models.IntegerField()),
            ],
            options={
                'db_table': 'redive_cn"."wave_group_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ENClanBattleBossGroup',
            fields=[
                ('id', models.IntegerField(db_column='clan_battle_boss_group_id', primary_key=True, serialize=False)),
                ('order_num', models.IntegerField()),
                ('wave_group_id', models.IntegerField()),
                ('score_coefficient', models.FloatField()),
            ],
            options={
                'db_table': 'redive_en"."clan_battle_boss_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ENClanBattleMapData',
            fields=[
                ('id', models.IntegerField(db_column='clan_battle_id', primary_key=True, serialize=False)),
                ('lap_num_from', models.IntegerField()),
                ('lap_num_to', models.IntegerField()),
                ('boss_group_id', models.IntegerField(db_column='clan_battle_boss_group_id')),
            ],
            options={
                'db_table': 'redive_en"."clan_battle_map_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnemyParameter',
            fields=[
                ('id', models.IntegerField(db_column='enemy_id', primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField()),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('pdef', models.IntegerField(db_column='def')),
                ('mdef', models.IntegerField(db_column='magic_def')),
            ],
            options={
                'db_table': 'redive_en"."enemy_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JPClanBattleMapData',
            fields=[
                ('id', models.IntegerField(db_column='clan_battle_id', primary_key=True, serialize=False)),
                ('lap_num_from', models.IntegerField()),
                ('lap_num_to', models.IntegerField()),
                ('wave_group_id_1', models.IntegerField()),
                ('score_coefficient_1', models.FloatField()),
                ('wave_group_id_2', models.IntegerField()),
                ('score_coefficient_2', models.FloatField()),
                ('wave_group_id_3', models.IntegerField()),
                ('score_coefficient_3', models.FloatField()),
                ('wave_group_id_4', models.IntegerField()),
                ('score_coefficient_4', models.FloatField()),
                ('wave_group_id_5', models.IntegerField()),
                ('score_coefficient_5', models.FloatField()),
            ],
            options={
                'db_table': 'redive_jp"."clan_battle_2_map_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JPEnemyParameter',
            fields=[
                ('id', models.IntegerField(db_column='enemy_id', primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField()),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('pdef', models.IntegerField(db_column='def')),
                ('mdef', models.IntegerField(db_column='magic_def')),
            ],
            options={
                'db_table': 'redive_jp"."enemy_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JPWaveGroupData',
            fields=[
                ('id', models.IntegerField(db_column='wave_group_id', primary_key=True, serialize=False)),
                ('odds', models.IntegerField()),
                ('enemy_id_1', models.IntegerField()),
            ],
            options={
                'db_table': 'redive_jp"."wave_group_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaveGroupData',
            fields=[
                ('id', models.IntegerField(db_column='wave_group_id', primary_key=True, serialize=False)),
                ('odds', models.IntegerField()),
                ('enemy_id_1', models.IntegerField()),
            ],
            options={
                'db_table': 'redive_en"."wave_group_data',
                'managed': False,
            },
        ),
    ]
