# Generated by Django 3.2 on 2021-06-02 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0027_auto_20210602_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clanbattle',
            old_name='begin_time',
            new_name='start_time',
        ),
    ]
