# Generated by Django 3.2.3 on 2021-06-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0031_team_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAlias',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='unit_name')),
            ],
            options={
                'db_table': 'rongbot"."unit_alias',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='clanbattlebossinfo',
            name='boss1_iconid',
        ),
        migrations.RemoveField(
            model_name='clanbattlebossinfo',
            name='boss2_iconid',
        ),
        migrations.RemoveField(
            model_name='clanbattlebossinfo',
            name='boss3_iconid',
        ),
        migrations.RemoveField(
            model_name='clanbattlebossinfo',
            name='boss4_iconid',
        ),
        migrations.RemoveField(
            model_name='clanbattlebossinfo',
            name='boss5_iconid',
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='boss1_iconid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='boss2_iconid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='boss3_iconid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='boss4_iconid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='boss5_iconid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
