# Generated by Django 3.2.3 on 2021-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0032_auto_20210606_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discriminator',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
