# Generated by Django 3.2.3 on 2021-06-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0033_user_discriminator'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMember',
            fields=[
                ('member_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('username', models.TextField()),
                ('discriminator', models.IntegerField()),
            ],
            options={
                'db_table': 'rongbot"."discord_members',
                'managed': False,
            },
        ),
    ]
