# Generated by Django 3.2.3 on 2021-06-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0035_alter_clanmember_is_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clans',
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rong.clan'),
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_memberships', to='rong.user'),
        ),
    ]
