# Generated by Django 3.2.3 on 2021-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0037_user_clans'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServerRole',
            fields=[
                ('server_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('role_id', models.CharField(max_length=30)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'rongbot"."discord_server_roles',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DiscordServerRoles',
        ),
    ]
