# Generated by Django 3.2.3 on 2021-06-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0038_auto_20210607_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='game_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanmember',
            name='ign',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
