# Generated by Django 3.2.3 on 2021-06-19 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0039_auto_20210619_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clanmember',
            old_name='game_id',
            new_name='player_id',
        ),
    ]
