# Generated by Django 3.2.3 on 2021-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0041_auto_20210620_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanbattlescore',
            name='killing_blow',
            field=models.BooleanField(default=False),
        ),
    ]
