# Generated by Django 3.2.3 on 2021-06-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0044_clanbattlescore_ign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='unit1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='unit1teams', to='rong.unit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='unit2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='unit2teams', to='rong.unit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='unit3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='unit3teams', to='rong.unit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='unit4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='unit4teams', to='rong.unit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='unit5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='unit5teams', to='rong.unit'),
        ),
    ]
