# Generated by Django 3.2.3 on 2021-06-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0045_auto_20210622_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlearenacounter',
            name='attacker_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker_in',
                                    to='rong.team'),
        ),
        migrations.AlterField(
            model_name='battlearenacounter',
            name='defender_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_in',
                                    to='rong.team'),
        ),
        migrations.AlterField(
            model_name='clanbattlecomp',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rong.team'),
        ),
        migrations.AlterField(
            model_name='clanbattlescore',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rong.team'),
        ),
        migrations.AlterField(
            model_name='princessarenacomp',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_for',
                                    to='rong.team'),
        ),
        migrations.AlterField(
            model_name='princessarenacomp',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_for',
                                    to='rong.team'),
        ),
        migrations.AlterField(
            model_name='princessarenacomp',
            name='team3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team3_for',
                                    to='rong.team'),
        ),
    ]
