# Generated by Django 3.2.3 on 2021-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0046_auto_20210623_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpromotion',
            options={'managed': False, 'ordering': ['promotion_level']},
        ),
        migrations.RemoveField(
            model_name='clan',
            name='collection',
        ),
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ClanCollection',
        ),
    ]
