# Generated by Django 3.2.3 on 2021-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0047_auto_20210719_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanbattle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanbattle',
            name='viewable_by_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clanbattle',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clanbattle',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
