# Generated by Django 3.2.3 on 2021-07-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0048_auto_20210719_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_members',
                                    to='rong.clan'),
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_clan_memberships',
                                    to='rong.user'),
        ),
    ]
