# Generated by Django 3.2.3 on 2021-07-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0051_auto_20210721_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittag',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit_tags', to='rong.clan'),
        ),
        migrations.AlterField(
            model_name='hittag',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
