# Generated by Django 3.2.3 on 2021-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0052_auto_20210722_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clans',
        ),
        migrations.AlterField(
            model_name='clanbattlescore',
            name='tags',
            field=models.ManyToManyField(related_name='hits', to='rong.HitTag'),
        ),
    ]
