# Generated by Django 3.2.3 on 2021-11-25 16:06

from django.db import migrations, models
import django.db.models.deletion


def fill_score_member(apps, schema_editor):
    ClanBattleScore = apps.get_model("rong", "ClanBattleScore")
    ClanMember = apps.get_model("rong", "ClanMember")
    for score in ClanBattleScore.objects.select_related('clan_battle', 'user'):
        if score.member is None:
            m = ClanMember.objects.filter(user=score.user, clan=score.clan_battle.clan).first()
            if m is None:
                m = ClanMember(user=score.user, clan=score.clan_battle.clan, ign=score.user.name, is_lead=False,
                               active=False)
                m.save()
            score.member = m
            score.save()


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0054_auto_20211020_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanbattlescore',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rong.clanmember'),
        ),
        migrations.RunPython(fill_score_member),
    ]
