# Generated by Django 3.2.3 on 2021-11-25 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0055_clanbattlescore_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanbattlescore',
            name='ign',
        ),
        migrations.RemoveField(
            model_name='clanbattlescore',
            name='user',
        ),
    ]
