# Generated by Django 3.2.3 on 2021-11-26 11:39

from django.db import migrations, models
import django.db.models.deletion


def update_clan_boxes(apps, schema_editor):
    Box = apps.get_model("rong", "Box")
    for box in Box.objects.all():
        if hasattr(box, "clanmember"):
            box.user_id = None
            box.name = None
            box.save()
    ClanMember = apps.get_model("rong", "ClanMember")
    for cm in ClanMember.objects.all():
        if cm.box is None:
            cm.box = Box()
            cm.box.save()
            cm.save()
        if cm.ign == 'Unnamed' and cm.user is not None:
            cm.ign = cm.user.name[:20]
            cm.save()


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0057_auto_20211126_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rong.user'),
        ),
        migrations.RunPython(update_clan_boxes),
    ]
