# Generated by Django 3.2.3 on 2021-11-26 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0058_auto_20211127_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='single_mode',
        ),
    ]
