# Generated by Django 3.2.3 on 2021-12-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0062_auto_20211205_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueEquipmentEnhanceData',
            fields=[
                ('enhance_level', models.IntegerField(db_column='enhance_level', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'redive_en"."unique_equipment_enhance_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitUniqueEquip',
            fields=[
                ('id', models.AutoField(db_column='equip_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'redive_en"."unit_unique_equip',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='box',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='boxunit',
            name='notes',
            field=models.TextField(default='', max_length=300),
        ),
    ]
