# Generated by Django 3.2.3 on 2021-12-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0063_auto_20211205_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(db_column='item_id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='item_name')),
                ('item_type', models.IntegerField()),
                ('limit_num', models.IntegerField()),
            ],
            options={
                'db_table': 'redive_en"."item_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UnlockUnitCondition',
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='kyaru_pilot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilots', to='rong.clanmember'),
        ),
    ]
