# Generated by Django 3.2.3 on 2022-03-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0065_clan_box_summary_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanbattlecomp',
            name='borrowed_unit',
        ),
        migrations.RemoveField(
            model_name='clanbattlecomp',
            name='group',
        ),
        migrations.AddField(
            model_name='clanbattlecomp',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hits', to='rong.clanbattlecomp'),
        ),
    ]
