# Generated by Django 3.2.3 on 2022-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0066_auto_20220327_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanbattlescore',
            name='comp_locked',
            field=models.BooleanField(default=False),
        ),
    ]
