# Generated by Django 3.2.3 on 2022-04-21 07:27
import django
from django.db import migrations


def fix_teams(apps, schema_editor):
    from django.apps import apps
    Team = apps.get_model("rong", "Team")
    for t in Team.objects.all():
        t.fix_uid()  # quick set UIDs only
    for t in Team.objects.all():
        t.fix()  # ordering
    # now preload all teams to avoid weirdness with deleting them
    teams = list(Team.objects.all())
    for t in teams:
        t.deduplicate()


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0068_alter_clanbattlecomp_clan_battle'),
    ]

    operations = [
        migrations.RunPython(fix_teams),
    ]
