# Generated by Django 3.2.3 on 2022-07-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0069_fix_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rongbot"."flight',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('motto', models.TextField()),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rongbot"."pilot',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='clanbattlescore',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='boxunit',
            name='ex_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boxunit',
            name='s1_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boxunit',
            name='s2_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boxunit',
            name='ub_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
