# Generated by Django 3.2.3 on 2022-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0070_auto_20220708_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryDetail',
            fields=[
                ('id', models.IntegerField(db_column='story_id', primary_key=True, serialize=False)),
                ('love_level', models.IntegerField()),
            ],
            options={
                'db_table': 'redive_en"."story_detail',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='ingame_fulldata',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='ingame_log_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='ingame_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clanbattlescore',
            name='updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
