# Generated by Django 3.2.3 on 2022-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rong', '0071_auto_20220726_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENClanBattleMapData2',
            fields=[
                ('id', models.IntegerField(db_column='clan_battle_id', primary_key=True, serialize=False)),
                ('lap_num_from', models.IntegerField()),
                ('lap_num_to', models.IntegerField()),
                ('wave_group_id_1', models.IntegerField()),
                ('score_coefficient_1', models.FloatField()),
                ('wave_group_id_2', models.IntegerField()),
                ('score_coefficient_2', models.FloatField()),
                ('wave_group_id_3', models.IntegerField()),
                ('score_coefficient_3', models.FloatField()),
                ('wave_group_id_4', models.IntegerField()),
                ('score_coefficient_4', models.FloatField()),
                ('wave_group_id_5', models.IntegerField()),
                ('score_coefficient_5', models.FloatField()),
            ],
            options={
                'db_table': 'redive_en"."clan_battle_2_map_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForceQuit',
            fields=[
                ('time', models.TimeField(db_column='time_used', primary_key=True, serialize=False)),
                ('day', models.IntegerField(db_column='day_used')),
                ('note', models.TextField(null=True)),
            ],
            options={
                'db_table': 'rongbot"."force_quit',
                'managed': False,
            },
        ),
    ]
