# Generated by Django 3.2.3 on 2022-10-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rong', '0072_enclanbattlemapdata2_forcequit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity6QuestData',
            fields=[
                ('id', models.AutoField(db_column='rarity_6_quest_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'redive_en"."rarity_6_quest_data',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='clanmember',
            name='out_of_clan',
            field=models.BooleanField(default=False),
        ),
    ]
