from django.db import models

class ClanBattleScore(models.Model):
    clan_battle = models.ForeignKey('ClanBattle', on_delete=models.CASCADE)
    member = models.ForeignKey('Member', on_delete=models.CASCADE)
    boss_lap = models.IntegerField()
    boss_number = models.IntegerField()
    damage = models.IntegerField()
    unit1 = models.ForeignKey('Unit', null=True, related_name='unit1scores', on_delete=models.DO_NOTHING)
    unit1_star = models.IntegerField(null=True)
    unit1_damage = models.IntegerField(null=True)
    unit2 = models.ForeignKey('Unit', null=True, related_name='unit2scores', on_delete=models.DO_NOTHING)
    unit2_star = models.IntegerField(null=True)
    unit2_damage = models.IntegerField(null=True)
    unit3 = models.ForeignKey('Unit', null=True, related_name='unit3scores', on_delete=models.DO_NOTHING)
    unit3_star = models.IntegerField(null=True)
    unit3_damage = models.IntegerField(null=True)
    unit4 = models.ForeignKey('Unit', null=True, related_name='unit4scores', on_delete=models.DO_NOTHING)
    unit4_star = models.IntegerField(null=True)
    unit4_damage = models.IntegerField(null=True)
    unit5 = models.ForeignKey('Unit', null=True, related_name='unit5scores', on_delete=models.DO_NOTHING)
    unit5_star = models.IntegerField(null=True)
    unit5_damage = models.IntegerField(null=True)
