from django.db import models

class ClanBattleBossInfo(models.Model):
    clan_battle = models.ForeignKey('ClanBattle', on_delete=models.CASCADE, related_name='bosses')
    difficulty = models.PositiveIntegerField()
    lap_from = models.PositiveIntegerField()
    lap_to = models.PositiveIntegerField(null=True)
    boss1_name = models.CharField(max_length=50)
    boss1_hp = models.PositiveIntegerField()
    boss1_pdef = models.PositiveIntegerField()
    boss1_mdef = models.PositiveIntegerField()
    boss1_iconid = models.PositiveIntegerField(null=True)
    boss2_name = models.CharField(max_length=50)
    boss2_hp = models.PositiveIntegerField()
    boss2_pdef = models.PositiveIntegerField()
    boss2_mdef = models.PositiveIntegerField()
    boss2_iconid = models.PositiveIntegerField(null=True)
    boss3_name = models.CharField(max_length=50)
    boss3_hp = models.PositiveIntegerField()
    boss3_pdef = models.PositiveIntegerField()
    boss3_mdef = models.PositiveIntegerField()
    boss3_iconid = models.PositiveIntegerField(null=True)
    boss4_name = models.CharField(max_length=50)
    boss4_hp = models.PositiveIntegerField()
    boss4_pdef = models.PositiveIntegerField()
    boss4_mdef = models.PositiveIntegerField()
    boss4_iconid = models.PositiveIntegerField(null=True)
    boss5_name = models.CharField(max_length=50)
    boss5_hp = models.PositiveIntegerField()
    boss5_pdef = models.PositiveIntegerField()
    boss5_mdef = models.PositiveIntegerField()
    boss5_iconid = models.PositiveIntegerField(null=True)
