# Generated by Django 3.2 on 2021-04-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'redive_en"."unit_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('is_lead', models.BooleanField()),
                ('group_num', models.IntegerField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='webapp.clan')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_available', models.TextField()),
                ('available_length', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClanCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.member')),
            ],
        ),
        migrations.AddField(
            model_name='clan',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clans_administrated', to='webapp.member'),
        ),
        migrations.AddField(
            model_name='clan',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.clancollection'),
        ),
        migrations.CreateModel(
            name='AvailableUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('star', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('equip_1', models.IntegerField()),
                ('equip_2', models.IntegerField()),
                ('equip_3', models.IntegerField()),
                ('equip_4', models.IntegerField()),
                ('equip_5', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.unit')),
            ],
        ),
    ]
