# Generated by Django 3.2 on 2021-04-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanBattleSchedule',
            fields=[
                ('id', models.AutoField(db_column='clan_battle_id', primary_key=True, serialize=False)),
                ('release_month', models.IntegerField()),
                ('last_cb', models.IntegerField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
            ],
            options={
                'db_table': 'redive_en"."clan_battle_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClanBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.clan')),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.clanbattleschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ClanBattleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_lap', models.IntegerField()),
                ('boss_number', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('clan_battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.clanbattle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClanBattleComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_lap', models.IntegerField()),
                ('boss_number', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('borrowed_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowedcomps', to='webapp.unit')),
                ('clan_battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.clanbattle')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.member')),
                ('unit1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit1comps', to='webapp.unit')),
                ('unit2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit2comps', to='webapp.unit')),
                ('unit3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit3comps', to='webapp.unit')),
                ('unit4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit4comps', to='webapp.unit')),
            ],
        ),
    ]
