# Generated by Django 3.2 on 2021-04-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_clanbattle_clanbattlecomp_clanbattleschedule_clanbattlescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clanbattle',
            old_name='game_id',
            new_name='game_battle',
        ),
    ]
