name: deploy-prod
on:
  pull_request:
    branches:
      - prod
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Update deps and migrate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd RongWebapp
            source venv/bin/activate
            npm ci
            npm run build
            pip install -r requirements.txt
            python manage.py update_database en
            python manage.py update_database cn
            python manage.py update_database jp
            python manage.py migrate
            python manage.py collectstatic --no-input
