name: deploy-uat
on:
  push:
    branches:
      - uat
jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - run: npm ci

      - run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.UAT_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.UAT_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --checksum --exclude '.git' --exclude '.github' --exclude '.gitignore' --exclude 'node_modules' --exclude 'package.json' --exclude 'package-lock.json' --exclude 'src' --exclude 'webpack' --exclude 'webpack-stats.json' ./ ${{ secrets.UAT_SSH_USERNAME }}@${{ secrets.UAT_SSH_HOST }}:/home/${{ secrets.UAT_SSH_USERNAME }}/django/
      
      - name: Update deps and migrate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UAT_SSH_HOST }}
          username: ${{ secrets.UAT_SSH_USERNAME }}
          key: ${{ secrets.UAT_SSH_KEY }}
          port: 22
          script: |
            source ~/django-env/bin/activate
            cd ~/django
            pip install -r requirements.txt
            python manage.py update_database en
            python manage.py update_database cn
            python manage.py update_database jp
            python manage.py migrate
            python manage.py collectstatic --no-input --clear
