name: deploy-uat
on:
  push:
    branches:
      - uat
jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --exclude '.git' --exclude '.github' --exclude '.gitignore' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ronguat/django/
      
      - name: Update deps and migrate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            source ~/django-env/bin/activate
            cd ~/django
            pip install -r requirements.txt
            python manage.py update_database en
            python manage.py migrate
